### ISSUE TITLE
Cannot read property 'status' of undefined

### ISSUE THREAD

**Issue by funkybaboon** [lusarz/jira-node-cli#10]
When running `jira all` I get

```
$ jira all
TypeError: Cannot read property 'status' of undefined
    at handleResponseError (/usr/local/lib/node_modules/jira-node-cli/lib/utils/ErrorHandleUtils.js:12:49)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
I'm using node 8.9.3. Any hints?

**Comment by lusarz** [comment]
Thanks @funkybaboon for information. This error comes from:
https://github.com/lusarz/jira-node-cli/blob/4f4a745542076e57fa4994979b4097d7ec3df45e/lib/utils/ErrorHandleUtils.js#L12

seems like I incorrectly assumed that `err.response` returned with `axios` library is always defined. I'll improve error handling for this case until tomorrow.

**Comment by lusarz** [comment]
@funkybaboon 
I updated error handling in this scenario. You can update tool using `npm install -g jira-node-cli`, and after running `jira all` you should get more detailed error output. I would be grateful for information about error you get now - it will help me with further debugging.

Thanks for help!

**Comment by funkybaboon** [comment]
now i get
```
$ jira all
An unexpected error occurred during communication with JIRA: 
Code: ENOTFOUND
Syscall: getaddrinfo
Errno: ENOTFOUND
```

**Comment by lusarz** [comment]
It looks like known problem with NodeJS:
https://stackoverflow.com/questions/23259697/error-getaddrinfo-enotfound-in-nodejs-for-get-call

It may be related with https. Could you try to manually edit `.jirarc` file (placed in home directory), and change `API_URL`:
`https://<your-org-name>.atlassian.net` into `http://<your-org-name>.atlassian.net` ?

**Comment by funkybaboon** [comment]
The error was that in the setup I entered the org name with `https`
```
https://<your-org-name>.atlassian.net
```
instead of 
```
<your-org-name>.atlassian.net
```
This resulted in an incorrect entry in the `.jirarc`:
```
{
  "API_URL": "https://https://<your-org-name>.atlassian.net",
  "TOKEN": "<your-token>"
}
```
After removing the obsolete `https` it works now. Thanks for looking into 👍

**Comment by lusarz** [comment]
You're welcome. That means I have to hurry up with https://github.com/lusarz/jira-node-cli/issues/1 implementation :)
