### ISSUE TITLE
jql can only pull back 50 rows

### ISSUE THREAD

**Issue by sethcenterbar** [lusarz/jira-node-cli#13]
First off, this is an amazing tool. Thanks for putting it out here, it's going to be super helpful for myself and my team!

It would be really great If I could pull back more than 50 rows. Has anyone else run into this limit? I imagine this may be api related (pagination?)

**Comment by sethcenterbar** [comment]
Did some more digging, it looks like pagination is likely the culprit.

In the resolution section, they mention having the client use pagination. 
https://confluence.atlassian.com/jirakb/changing-maxresults-parameter-for-jira-cloud-rest-api-779160706.html

I am definitely not a js dev, but I did some digging and I believe the fix could be in the function fetchIssuesUsingJQL() on line 19 of  jira-node-cli/lib/dao/issues-dao.js

Could be wrong about that, but I wanted to at least make an effort to help.

**Comment by lusarz** [comment]
Hello Seth, thank you for kind words about this tool, I'm very happy that it's helpful for you and your team :)

I've [increased `maxResults`](https://github.com/lusarz/jira-node-cli/commit/62b57c7e183ab35d0bf96df1633010ee24d7efe8) and [published](https://www.npmjs.com/package/jira-node-cli/v/1.2.1) new version of jira-node-cli. Unfortunately I met issue described [here](https://community.atlassian.com/t5/Jira-questions/How-to-get-more-than-50-issues-with-search-API/qaq-p/463122#M233628) - JIRA limits response to max 100 results, even if I pass bigger number.

**Comment by sethcenterbar** [comment]
Thanks for doing that @lusarz , i really appreciate it!
